baseURL: "https://74tomneal.com"
title: Context Switch
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: development
    title: Context Switch
    description: "74 Tom Neal Drive, Orcacoke, North"
    author: ["Sarah Funkhouser","Christian Funkhouser"]

    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false

    label:
        text: "Context.Switch"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Context Switch
        imageUrl: 'home2.jpg'
        imageTitle: my image
        buttons:
            - name: House Layout
              url: layout
            - name: Amenities
              url: amenities

    # home-info mode
    homeInfoParams:
        Title: "Context Switch"
        Content: 74 Tom Neal Drive, Ocracoke, North Carolina

    socialIcons:
        - name: instagram
          url: "https://www.instagram.com/contextswitch.ocracoke/"

menu:
    main:
        - identifier: details
          name: details
          url: /details/
          weight: 10
        - identifier: availability
          name: availability
          url: /availability/
          weight: 20
        - identifier: contact
          name: contact
          url: /contact/
          weight: 30